export const siteConfig = {
  name: "Shopi",
  tagline: "Kenya's social discovery classifieds marketplace",
  description:
    "Shopi is Kenya's social discovery classifieds marketplace for buyers and sellers. Discover cars, phones, fashion, furniture, farm produce, livestock and everyday finds in a personalized nearby feed, then message the seller directly. Shopi does not process payments, take commission or sit between the deal.",
  // Default canonical domain. Override per-environment with NEXT_PUBLIC_APP_URL.
  url: process.env.NEXT_PUBLIC_APP_URL || "https://shopi.co.ke",
  // The site-wide OG card is rendered by app/[lang]/opengraph-image.tsx, so the
  // URL must carry the default locale prefix to resolve (bare /opengraph-image 404s).
  ogImage: "/en/opengraph-image",
  twitterHandle: "@shopiapp",
  locale: "en-KE",
  themeColor: "#E0005C",

  // Primary search/discovery terms we want Shopi to surface for.
  keywords: [
    "Shopi",
    "Shopi Kenya",
    "local marketplace Kenya",
    "social marketplace Kenya",
    "social discovery marketplace",
    "social discovery classifieds",
    "buy and sell Kenya",
    "classifieds Kenya",
    "classified ads Kenya",
    "marketplace Kenya",
    "online marketplace Kenya",
    "nearby marketplace Kenya",
    "discover products near me Kenya",
    "personalized shopping feed Kenya",
    "cows for sale Kenya",
    "livestock for sale Kenya",
    "farm produce Kenya",
    "cars for sale Kenya",
    "phones for sale Kenya",
    "Samsung phones for sale Kenya",
    "Samsung for sale Kenya",
    "iPhone for sale Kenya",
    "used phones for sale Kenya",
    "televisions for sale Kenya",
    "TVs for sale Kenya",
    "smart TVs for sale Kenya",
    "laptops for sale Kenya",
    "electronics for sale Kenya",
    "phone accessories Kenya",
    "furniture for sale Kenya",
    "fashion marketplace Kenya",
    "sell online Kenya",
    "sites to sell in Kenya",
    "sell items online Kenya",
    "sell a car in Kenya",
    "sell my car Kenya",
    "used cars for sale Kenya",
    "land for sale Kenya",
    "plots for sale Kenya",
    "property for sale Kenya",
    "houses for sale Kenya",
    "houses for rent Kenya",
    "plots for sale in Nyahururu",
    "plots for sale in Nyandarua",
    "property for sale Nairobi",
    "beauty products Kenya",
    "cosmetics Kenya",
    "skincare products Kenya",
    "makeup for sale Kenya",
    "hair products Kenya",
    "Jiji alternative Kenya",
    "TikTok marketplace Kenya",
    "Nairobi marketplace",
    "Mombasa marketplace",
    "Kisumu marketplace",
    "Nakuru marketplace",
    "Meru marketplace",
  ],

  routes: {
    feed: {
      path: "/feed",
      title: "Feed",
      description:
        "Scroll a feed of real products from sellers near you, then message them directly.",
    },
    explore: {
      path: "/explore",
      title: "Explore",
      description:
        "Discover what's for sale near you, or ask the Shopi assistant to find it for you.",
    },
    search: {
      path: "/search",
      title: "Search",
      description:
        "Search cars, phones, fashion, furniture, farm produce and more from sellers across Kenya.",
    },
    notifications: {
      path: "/notifications",
      title: "Inbox",
      description: "Your messages and activity on Shopi.",
    },
    profile: {
      path: "/profile",
      title: "Profile",
      description: "Your Shopi profile, posts, and settings.",
    },
    upload: {
      path: "/upload",
      title: "Create a Post",
      description:
        "Post what you're selling — add a video, a price, and your location.",
    },
  },
} as const;
