export const siteConfig = {
  name: "Shopi",
  tagline: "Kenya's local marketplace, in one feed",
  description:
    "Shopi is Kenya's social discovery classifieds marketplace for buyers and sellers. Discover cars, phones, fashion, furniture, farm produce, livestock and everyday finds in a personalized nearby feed, then message the seller directly. Shopi does not process payments, take commission or sit between the deal.",
  // Default canonical domain. Override per-environment with NEXT_PUBLIC_APP_URL.
  url: process.env.NEXT_PUBLIC_APP_URL || "https://shopi.co.ke",
  ogImage: "/opengraph-image",
  twitterHandle: "@shopiapp",
  locale: "en-KE",
  themeColor: "#7c3aed",

  // Primary search/discovery terms we want Shopi to surface for.
  keywords: [
    "Shopi",
    "Shopi Kenya",
    "local marketplace Kenya",
    "social marketplace Kenya",
    "social discovery marketplace",
    "social discovery classifieds",
    "buy and sell Kenya",
    "classifieds Kenya",
    "classified ads Kenya",
    "marketplace Kenya",
    "online marketplace Kenya",
    "nearby marketplace Kenya",
    "discover products near me Kenya",
    "personalized shopping feed Kenya",
    "cows for sale Kenya",
    "livestock for sale Kenya",
    "farm produce Kenya",
    "cars for sale Kenya",
    "phones for sale Kenya",
    "furniture for sale Kenya",
    "fashion marketplace Kenya",
    "sell online Kenya",
    "Jiji alternative Kenya",
    "TikTok marketplace Kenya",
    "Nairobi marketplace",
    "Mombasa marketplace",
    "Kisumu marketplace",
    "Nakuru marketplace",
    "Meru marketplace",
  ],

  routes: {
    feed:          { path: "/feed",          title: "Feed",          description: "Scroll a feed of real products from sellers near you, then message them directly." },
    explore:       { path: "/explore",       title: "Explore",       description: "Discover what's for sale near you, or ask the Shopi assistant to find it for you." },
    search:        { path: "/search",        title: "Search",        description: "Search cars, phones, fashion, furniture, farm produce and more from sellers across Kenya." },
    notifications: { path: "/notifications", title: "Inbox",         description: "Your messages and activity on Shopi." },
    profile:       { path: "/profile",       title: "Profile",       description: "Your Shopi profile, posts, and settings." },
    upload:        { path: "/upload",        title: "Create a Post", description: "Post what you're selling — add a video, a price, and your location." },
  },
} as const;
