import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const FALLBACK_FRONTEND_URL = "https://shopi.co.ke";

function frontendUrl(): string {
  const value =
    process.env.FRONTEND_URL ??
    process.env.NEXT_PUBLIC_APP_URL ??
    FALLBACK_FRONTEND_URL;

  try {
    return new URL(value).origin;
  } catch {
    return FALLBACK_FRONTEND_URL;
  }
}

/**
 * The worker must be generated by Next instead of living in `public`: a public
 * file is static and therefore cannot use FRONTEND_URL. This keeps notification
 * clicks on the canonical frontend even when an API payload contains a stale
 * localhost/development absolute URL.
 */
export async function GET() {
  const script = `
const APP_ORIGIN = ${JSON.stringify(frontendUrl())};
const DEFAULT_PATH = "/en";

function notificationUrl(value) {
  try {
    const incoming = new URL(
      typeof value === "string" && value ? value : DEFAULT_PATH,
      APP_ORIGIN,
    );
    // A push payload may carry an absolute URL created by another environment.
    // Keep the intended path, query and hash, but always use this deployment's
    // canonical frontend origin.
    return new URL(
      incoming.pathname + incoming.search + incoming.hash,
      APP_ORIGIN,
    ).href;
  } catch {
    return new URL(DEFAULT_PATH, APP_ORIGIN).href;
  }
}

self.addEventListener("push", (event) => {
  let payload = {};
  try {
    payload = event.data ? event.data.json() : {};
  } catch {
    // Invalid push payloads should still display a safe, useful notification.
  }

  const title = payload.title || "Shopi";
  const url = notificationUrl(payload.url || payload.data?.url);
  const options = {
    body: payload.body || "You have a new message",
    icon: payload.icon || "/assets/shopi-logo.png",
    badge: payload.badge || "/assets/shopi-logo.png",
    tag: payload.tag || "shopi-message",
    data: { ...(payload.data || {}), url },
  };

  const broadcastToClients = clients
    .matchAll({ type: "window", includeUncontrolled: true })
    .then((windowClients) =>
      Promise.all(
        windowClients.map((client) =>
          client.postMessage({
            type: "shopi:push",
            payload: { title, body: options.body, url, tag: options.tag },
          }),
        ),
      ),
    );

  event.waitUntil(
    Promise.all([
      self.registration.showNotification(title, options),
      broadcastToClients,
    ]),
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = notificationUrl(
    event.notification.data?.url || event.notification.data?.conversationUrl,
  );

  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then(async (windowClients) => {
      const client = windowClients[0];
      if (client) {
        await client.navigate(url);
        return client.focus();
      }

      return clients.openWindow(url);
    }),
  );
});
`;

  return new NextResponse(script, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
