"use client";

import { Plus, X } from "lucide-react";
import type { Spec } from "@/stores/create";

interface Props {
  specs: Spec[];
  onChange: (specs: Spec[]) => void;
  /** Show a subtle "generated by AI" hint above the list. */
  aiGenerated?: boolean;
}

/**
 * Key/value spec editor used in the create flow.
 *
 * Rules (per product spec):
 *  - Each row is a key + value pair.
 *  - "Add" is disabled while the last row has an empty key OR value, so you
 *    can't stack blank rows.
 *  - Any row can be removed.
 */
export function SpecsEditor({ specs, onChange, aiGenerated }: Props) {
  const lastRow = specs[specs.length - 1];
  const canAdd =
    specs.length === 0 ||
    (!!lastRow && lastRow.key.trim() !== "" && lastRow.value.trim() !== "");

  function updateRow(index: number, patch: Partial<Spec>) {
    onChange(specs.map((s, i) => (i === index ? { ...s, ...patch } : s)));
  }

  function removeRow(index: number) {
    onChange(specs.filter((_, i) => i !== index));
  }

  function addRow() {
    if (!canAdd) return;
    onChange([...specs, { key: "", value: "" }]);
  }

  return (
    <div>
      <div className="mb-1.5 flex items-center justify-between">
        <label
          className="font-medium"
          style={{
            fontSize: "var(--text-sm)",
            color: "rgb(var(--color-text-muted))",
          }}
        >
          Specifications
        </label>
        {aiGenerated && specs.length > 0 && (
          <span
            className="inline-flex items-center gap-1 rounded-full px-2 py-0.5"
            style={{
              fontSize: "var(--text-xs)",
              backgroundColor: "rgb(var(--brand-primary) / 0.12)",
              color: "rgb(var(--brand-primary))",
              fontWeight: 500,
            }}
          >
            ✨ AI generated
          </span>
        )}
      </div>

      <div className="flex flex-col gap-2">
        {specs.map((spec, i) => (
          <div key={i} className="flex items-center gap-2">
            <input
              value={spec.key}
              onChange={(e) => updateRow(i, { key: e.target.value })}
              placeholder="Attribute (e.g. Make)"
              className="min-w-0 flex-1 rounded-xl px-3 outline-none"
              style={{
                height: 44,
                fontSize: "var(--text-base)",
                color: "rgb(var(--color-text))",
                backgroundColor: "rgb(var(--color-bg-subtle))",
                border: "1px solid rgb(var(--color-border))",
                caretColor: "rgb(var(--brand-primary))",
              }}
            />
            <input
              value={spec.value}
              onChange={(e) => updateRow(i, { value: e.target.value })}
              placeholder="Value (e.g. Mazda)"
              className="min-w-0 flex-1 rounded-xl px-3 outline-none"
              style={{
                height: 44,
                fontSize: "var(--text-base)",
                color: "rgb(var(--color-text))",
                backgroundColor: "rgb(var(--color-bg-subtle))",
                border: "1px solid rgb(var(--color-border))",
                caretColor: "rgb(var(--brand-primary))",
              }}
            />
            <button
              type="button"
              onClick={() => removeRow(i)}
              className="flex shrink-0 items-center justify-center rounded-full"
              style={{
                width: 36,
                height: 36,
                color: "rgb(var(--color-text-muted))",
                backgroundColor: "rgb(var(--color-bg-subtle))",
              }}
              aria-label="Remove specification"
            >
              <X size={16} />
            </button>
          </div>
        ))}
      </div>

      <button
        type="button"
        onClick={addRow}
        disabled={!canAdd}
        className="mt-2 inline-flex items-center gap-1.5 rounded-xl px-3 py-2 font-medium transition-opacity"
        style={{
          fontSize: "var(--text-sm)",
          color: canAdd
            ? "rgb(var(--brand-primary))"
            : "rgb(var(--color-text-muted))",
          backgroundColor: canAdd
            ? "rgb(var(--brand-primary) / 0.12)"
            : "rgb(var(--color-bg-subtle))",
          opacity: canAdd ? 1 : 0.6,
          cursor: canAdd ? "pointer" : "not-allowed",
        }}
      >
        <Plus size={15} /> Add specification
      </button>
      {!canAdd && (
        <p
          className="mt-1"
          style={{
            fontSize: "var(--text-xs)",
            color: "rgb(var(--color-text-muted))",
          }}
        >
          Fill in the current row before adding another
        </p>
      )}
    </div>
  );
}
